### ISSUE TITLE
Migration from the latest groupmanager to the latest luckperms failed.

### ISSUE THREAD

**Issue by Rainaftbow** [LuckPerms/migration#8]
Description
While using luckperms-migration-groupmanager.jar on the latest version on Paper 1.20.1 and with the latest groupmanager version. It doesn't finish the migration:

Reproduction Steps
Everything said on the wiki.

Expected Behaviour
To have migrated but nothing is actually migrated.

LuckPerms Version
v5.4.137

Groupmanager version
v3.2

Logs and Configs
[13:22:06 INFO]: [luckperms-migration-groupmanager] Starting.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Starting global group migration.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 1 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 2 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 3 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 4 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 5 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 6 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 7 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 8 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 9 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 10 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 11 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 12 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 13 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 14 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 15 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 16 groups so far.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 16 global groups
[13:22:06 INFO]: [luckperms-migration-groupmanager] Collecting user and group data.
[13:22:06 INFO]: [luckperms-migration-groupmanager] Querying world world
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 1 groups so far in world world
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 2 groups so far in world world
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 3 groups so far in world world
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 4 groups so far in world world
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 5 groups so far in world world
[13:22:06 INFO]: [luckperms-migration-groupmanager] Migrated 5 groups in world world
[13:22:06 WARN]: [luckperms-migration-groupmanager] Plugin luckperms-migration-groupmanager v1 generated an exception while executing task 86922
java.lang.NoSuchMethodError: 'org.anjocaido.groupmanager.data.UserVariables org.anjocaido.groupmanager.data.User.getVariables()'
        at me.lucko.luckperms.migration.MigrationGroupManager.lambda$runMigration$5(MigrationGroupManager.java:191) ~[luckperms-migration-groupmanager.jar:?]
        at me.lucko.luckperms.migration.Iterators.tryIterate(Iterators.java:38) ~[luckperms-migration-groupmanager.jar:?]
        at me.lucko.luckperms.migration.MigrationGroupManager.lambda$runMigration$6(MigrationGroupManager.java:159) ~[luckperms-migration-groupmanager.jar:?]
        at me.lucko.luckperms.migration.Iterators.tryIterate(Iterators.java:51) ~[luckperms-migration-groupmanager.jar:?]
        at me.lucko.luckperms.migration.MigrationGroupManager.runMigration(MigrationGroupManager.java:118) ~[luckperms-migration-groupmanager.jar:?]
        at me.lucko.luckperms.migration.MigrationJavaPlugin.lambda$onCommand$0(MigrationJavaPlugin.java:37) ~[luckperms-migration-groupmanager.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-196]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

Extra Details
No response

**Comment by YuanYuanOwO** [comment]
If you still require it, please try this version.
https://github.com/Tianji-Server/migration-luckperms/releases
